title: Cory Sulpizi
logo: "/images/Cory.png?raw=true" 
description: > 
  M.Eng, University of Toronto<br>
  -----------------------------------<br>
  software engineer<br>
  e: csulpz@gmail.com<br>
  <a href="https://github.com/csulpizi">github profile</a>

footer-links:
  email: "csulpz@gmail.com"

theme: jekyll-theme-architect

sass:
  style: :expanded
#google_analytics: <tracking-id>
